version: "3.3"

services:
        db:
                image: mariadb:latest
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: Root0
                        MYSQL_DATABASE: project
                        MYSQL_USER: order
                        MYSQL_PASSWORD: order
                ports: 
                        - 3307:3306
                networks:
                        - myproject
        
        redis:
                image: redis:latest
                restart: always
                ports: 
                        - 6380:6379
                networks:
                        - myproject
        
        node:
                image: node:latest
                restart: always
                volumes:
                        - ./:/usr/local/app
                working_dir: /usr/local/app
                command: node server/server.js
                ports:  
                        - 8091:8090
                networks:
                        - myproject

        nginx:
                image: nginx:latest
                restart: always
                volumes:
                        - $HOME/project/src:/var/www/html
                        - $HOME/project/src/nginx.ini:/etc/nginx/conf.d/default.conf
                depends_on:
                        - db
                        - redis
                        - node
                ports:
                        - 80:80
                networks:
                        -  myproject
        
networks:
        myproject: