version: "3.3"

services:
        postgres:
                image: postgres
                restart: always
                environment:
                        POSTGRES_PASSWORD: root123
                networks:
                        - myproject
        redis:
                image: redis
                restart: always
                ports: 
                        - 6379:6379
                networks:
                        - myproject
        php:
                build: ./src/php
                volumes:
                        - $HOME/3208project/src:/var/www/html
                restart: always
                expose:
                        - "9000"
                depends_on:
                        - postgres
                        - redis
                networks: 
                        - myproject
        adminer:
                image: adminer
                #build: ./src/adminer
                restart: always
                ports:
                        - 8080:8080
                networks: 
                        - myproject
        nginx:
                image: nginx
                restart: always
                volumes:
                        - $HOME/3208project/src:/var/www/html
                        - $HOME/3208project/src/nginx.ini:/etc/nginx/conf.d/default.conf
                depends_on:
                        - postgres
                        - redis
                        - php
                ports:
                        - 80:80
                networks:
                        -  myproject
        
networks:
        myproject: