version: "3.3"

services:
        mongodb:
                image: mongo
                volumes:
                - "./mongodb/db:/data/db"
                ports:
                - "27017:27017"
                environment:
                        MONGO_INITDB_DATABASE: test
                        MONGO_INITDB_ROOT_USERNAME: root
                        MONGO_INITDB_ROOT_PASSWORD: 1234
                networks:
                        - myproject
        redis:
                image: redis
                restart: always
                ports: 
                        - 6379:6379
                networks:
                        - myproject
        php:
                build: ./src/php
                volumes:
                        - $HOME/3208project/src:/var/www/html
                restart: always
                expose:
                        - "9000"
                depends_on:
                        - mongodb
                        - redis
                networks: 
                        - myproject
        adminer:
                image: adminer
                restart: always
                ports:
                        - 8080:8080
                networks: 
                        - myproject
        nginx:
                image: nginx
                restart: always
                volumes:
                        - $HOME/3208project/src:/var/www/html
                        - $HOME/3208project/src/nginx.ini:/etc/nginx/conf.d/default.conf
                depends_on:
                        - mongodb
                        - redis
                        - php
                ports:
                        - 80:80
                networks:
                        -  myproject
        
networks:
        myproject: