FROM php:7.4-fpm
#RUN apt-get update
#apt-get install -y libpq-dev \
RUN pecl install igbinary \
	&& pecl install redis \
	&& docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install pgsql pdo_pgsql \
	&& docker-php-ext-enable redis \
	&& echo "extension=redis.so" > /usr/local/etc/php/conf.d/redis.ini