FROM php:7.4-fpm

RUN pecl install igbinary \
	&& pecl install redis \
	&& pecl install mongodb \
    && echo "extension=mongodb.so" > $PHP_INI_DIR/conf.d/mongo.ini\
	&& docker-php-ext-enable redis \
	&& echo "extension=redis.so" > /usr/local/etc/php/conf.d/redis.ini